name: textbook

channels:
  - conda-forge

dependencies:
  - pip:
    - bs4
    - tqdm
    - numpy
    - pyyaml
    - nbformat
    - nbclean
    - pandas
    - scipy
    - sklearn
    - seaborn
    - sunpy
    - astropy
    - mpld3
    - matplotlib
    - urllib
    - json
    - datetime
    - lime
    - os
    - time
    - torch
