name: textbook

channels:
  - conda-forge

dependencies:
  - pip:
    - bs4
    - tqdm
    - numpy
    - pyyaml
    - nbformat
    - nbclean
    - pandas
    - scipy
    - sklearn
    - seaborn
    - sunpy==0.9.5
    - suds-jurko
    - astropy==3.1
    - drms
    - mpld3
    - matplotlib
    - datetime
    - lime
    - torch
    - keras
    - jupyter_contrib_nbextensions
